#!/bin/bash

# Usage: uv run scripts/publish [--bump]
#
# If --bump is provided, the version will be bumped in pyproject.toml before publishing (with confirmation prompt).

set -e 

source scripts/.common

[[ "$PYPI_TOKEN" != pypi-* ]] && {
    .error "PYPI_TOKEN env var is either not set or invalid. Current value of PYPI_TOKEN='${PYPI_TOKEN}'"
    exit 1
}

[[ "$1" == "--bump" ]] && {
    uv run scripts/bumpversion.py || {
        # Confirm with the user to proceed
        read -p "Version was not bumped. Continue with publish? (y/n): " confirm
        [[ "$confirm" == [yY] ]] || exit 1
    }
}

# Build the package
uv run scripts/build

# Upload the package to PyPI
uv publish --token "$PYPI_TOKEN" || {
    .error "Failed to publish the package to PyPI"
    exit 1
}

.success "Published sticklight-python to PyPI."
