name: Publish Sticklight to PyPI

on:
  workflow_dispatch:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: read

jobs:
  test-build-release-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
          
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.11"
          enable-cache: true
          cache-dependency-glob: |
            "pyproject.toml"
            "uv.lock"
      
      - name: Install Python
        run: uv python install 3.11
    
      - name: Install the project
        run: uv sync --dev
      
      - name: Run tests
        run: uv run scripts/test
        
      - name: Build release distributions
        run: |
          uv run scripts/build
  
      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          password: ${{ secrets.PYPI_PUBLISH_TOKEN }}
  
  
      - name: Finish
        run: echo "Package version $VERSION published to PyPI successfully"
    
    environment:
      name: pypi
      url: https://pypi.org/p/sticklight
    permissions:
      id-token: write
